# Generated by Django 5.1 on 2025-03-29 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment_operator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.district'),
        ),
        migrations.AddField(
            model_name='order',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('ready_to_order', 'Ready To Order'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('not_pick_up', 'Not Pick Up'), ('archived', 'Archived')], default='new', max_length=20),
        ),
    ]
